name: DCGAN Training

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run setup
      run: python setup.py
    
    - name: Test training script
      run: python train.py --create-config --epochs 1 --batch-size 16
    
    - name: Test Streamlit app
      run: |
        python -c "import streamlit_app; print('Streamlit app imports successfully')"
